version: '3.7'
services:
  django-db:
    image: mysql:8.0
    container_name: django-db
    ports:
      - "33306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=django
      - MYSQL_DATABASE=django-db
    volumes:
     - ./django-db/data:/var/lib/mysql
